v = input("Digite algo: ")
# print("O tipo primitivo desse valor é:", type(v))
# print("Essa variavel só tem espaços?", v.isspace())
# print("É numero?", v.isnumeric())
# print("É alfabetico?", v.isalpha())
# print("É alfanumérico?", v.isalnum())
# print("Está maiúscula?", v.isupper())
# print("Está capitalizada?", v.istitle())
print(f"Dissecando o variavel digitada, percebesse que a mesma se inicia com letra maiúscula {v.istitle()}")